drop table if exists product CASCADE;

create table DJIndex (index_id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) primary key , quarter integer ,stock varchar(255) ,date varchar(255),open varchar(255) ,high varchar(255),low varchar(255),close varchar(255),volume integer,percent_change_price double,percent_change_volume_over_last_wk double,previous_weeks_volume integer ,next_weeks_open varchar(255),next_weeks_close varchar(255),percent_change_next_weeks_price double,days_to_next_dividend integer,percent_return_next_dividend double);
